version: "3.7"
services:
  php:
    build:
      dockerfile: php/php.Dockerfile
      context: .
    volumes:
      - ./src/backend:/var/www/backend/
    depends_on:
      - db
    networks:
      - backend
      - frontend
    ports:
      - 9000:9000
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=giftcard
      - POSTGRES_USER=totalchallenge
      - POSTGRES_PASSWORD=5678465
    networks:
      - backend
    ports:
      - 5432:5432
  web:
    image: nginx:latest
    volumes:
      - ./src/:/var/www/
      - ./nginx/config/:/etc/nginx/conf.d/
      - ./nginx/snippets/:/etc/nginx/snippets/
    depends_on:
      - php
      - front
    networks:
      - backend
      - frontend
    ports:
      - 80:80
  front:
    image: node:14
    volumes:
      - ./src/frontend:/var/www/frontend
    ports:
      - 3000:3000
      - 35729:35729
    networks:
      - frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
